import PDFDocument from 'pdfkit';

function formatAnswer(answer) {
  if (typeof answer === 'boolean') {
    return answer ? 'Yes' : 'No';
  } else if (answer === null || answer === undefined) {
    return 'Not answered';
  } else {
    return String(answer);
  }
}

function getAnswerColors(answer) {
  if (typeof answer === 'boolean') {
    if (answer) {
      return { bg: [212, 237, 218], text: [21, 87, 36], border: [195, 230, 203] };
    } else {
      return { bg: [248, 215, 218], text: [114, 28, 36], border: [245, 198, 203] };
    }
  }
  return { bg: [231, 243, 255], text: [0, 64, 133], border: [184, 218, 255] };
}

export async function generatePdfFromTranscript(report) {
  return new Promise((resolve, reject) => {
    try {
      console.log('[PDF Generator] Starting PDF generation...');
      console.log(`[PDF Generator] Report contains ${report.length} questions`);

      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 }
      });

      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        console.log(`[PDF Generator] ✓ PDF generated successfully (${pdfBuffer.length} bytes)`);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      doc.fontSize(24).fillColor('#0078d4').text('Health Assessment Report', { align: 'center' });
      doc.fontSize(14).fillColor('#666666').text('Respiratory Health Screening', { align: 'center' });
      doc.fontSize(10).fillColor('#999999').text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });
      doc.moveDown(2);
      doc.strokeColor('#0078d4').lineWidth(2).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(1.5);

      report.forEach((item, index) => {
        const question = item.question || 'No question';
        const answer = item.answer;
        const formattedAnswer = formatAnswer(answer);
        const colors = getAnswerColors(answer);

        if (doc.y > 700) {
          doc.addPage();
        }

        const badgeX = 50;
        const badgeY = doc.y;
        const badgeWidth = 40;
        const badgeHeight = 20;

        doc.fillColor('#0078d4').roundedRect(badgeX, badgeY, badgeWidth, badgeHeight, 3).fill();
        doc.fillColor('#ffffff').fontSize(10).text(`Q${index + 1}`, badgeX, badgeY + 5, { width: badgeWidth, align: 'center' });
        doc.moveDown(0.3);
        doc.fillColor('#333333').fontSize(12).text(question, { width: 495, align: 'left' });
        doc.moveDown(0.5);
        doc.fillColor('#666666').fontSize(9).text('ANSWER:', { continued: false });
        doc.moveDown(0.3);

        const answerBoxY = doc.y;
        const answerBoxHeight = 30;

        doc.fillColor(colors.bg[0] / 255, colors.bg[1] / 255, colors.bg[2] / 255).roundedRect(50, answerBoxY, 495, answerBoxHeight, 5).fill();
        doc.strokeColor(colors.border[0] / 255, colors.border[1] / 255, colors.border[2] / 255).lineWidth(1).roundedRect(50, answerBoxY, 495, answerBoxHeight, 5).stroke();
        doc.fillColor(colors.text[0] / 255, colors.text[1] / 255, colors.text[2] / 255).fontSize(11).text(formattedAnswer, 60, answerBoxY + 10, { width: 475, align: 'left' });

        doc.y = answerBoxY + answerBoxHeight;
        doc.moveDown(1.5);
      });

      doc.moveDown(2);
      doc.strokeColor('#dddddd').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor('#999999').text('This report was generated by Azure Health Bot Service', { align: 'center' });
      doc.text('Confidential - For authorized use only', { align: 'center' });

      doc.end();

    } catch (error) {
      console.error('[PDF Generator] ✗ PDF generation failed:', error.message);
      reject(new Error(`Failed to generate PDF: ${error.message}`));
    }
  });
}
